[workspace]
members = ["cli", "core", "download", "extract", "unity"]

[workspace.package]
authors = ["我可能很廢"]
edition = "2021"
license = "MIT"
repository = "https://github.com/nicks96432/mltd-asset-downloader"

[workspace.dependencies]
log = "0.4.17"
num_cpus = "1.15.0"
rayon = "1.6.1"

[workspace.dependencies.clap]
default-features = false
features = ["std", "help", "usage"]
version = "4.1.6"

[workspace.dependencies.env_logger]
default-features = false
features = ["humantime"]
version = "0.10.0"

[workspace.dependencies.indicatif]
default-features = false
features = ["rayon"]
version = "0.17.3"

[profile.release]
codegen-units = 12
lto = "thin"
panic = "abort"
strip = true
