[package]
authors = ["我可能很廢"]
categories = ["command-line-utilities"]
description = "asset downloader for THE IDOLM@STER MILLION LIVE! Theater Days (MLTD)"
edition = "2021"
homepage = "https://github.com/nicks96432/mltd-asset-downloader"
keywords = ["downloader", "MLTD", "mirishita", "theaterdays", "unpack"]
license = "MIT"
name = "mltd-asset-downloader"
readme = "README.md"
repository = "https://github.com/nicks96432/mltd-asset-downloader"
version = "0.1.0"

[dependencies]
clap-verbosity-flag = "2.0.0"
log = "0.4.17"
num_cpus = "1.15.0"
rmp-serde = "1.1.1"
rayon = "1.6.1"

[dependencies.clap]
default-features = false
features = ["std", "derive", "help", "usage"]
version = "4.1.4"

[dependencies.env_logger]
default-features = false
features = ["humantime"]
version = "0.10.0"

[dependencies.indicatif]
default-features = false
features = ["rayon"]
version = "0.17.3"

[dependencies.serde]
features = ["derive"]
version = "1.0.152"

[dependencies.ureq]
features = ["json", "native-certs"]
version = "2.6.2"

[features]
debug = []

[profile.release]
codegen-units = 12
lto = "thin"
panic = "abort"
strip = true
