workflows:
  aarch64-darwin-build
    environment:
      xcode: 13.3
    scripts:
      - name: Update submodule
        script: git submodule update --init --recursive
      - name: Install rust non-interactively
        script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      -name: Setup rust environment
        script: source $HOME/.cargo/env
      - name: Use nightly rust
        script: rustup default nightly
      - name: Build
        script: cargo build --release

    artifacts:
      - target/release/mltd
